// <auto-generated />
namespace vidlko.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class checkanyupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkanyupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202112291205099_checkanyupdates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
